from __future__ import annotations

from typing import Any

from prompt_runner import PromptRunner
from state import TechDailyState

from tech_daily.pipeline.state import ReportInputState

ROOT: str
DEFAULT_DAILY_MODEL: str

def _load_config() -> Any: ...
def _load_preferences() -> Any: ...
def _previous_reports_summary_from_input(input_state: ReportInputState) -> list[dict[str, Any]]: ...
def _safe_dict(obj: Any) -> Any: ...
def _build_report_payload(state: TechDailyState) -> dict[str, Any]: ...
def build_daily_report_payload_from_input(input_state: ReportInputState) -> dict[str, Any]: ...
def generate_daily_report(state: TechDailyState, prompt_runner: PromptRunner | None = ...) -> str: ...
def generate_daily_report_from_input(
    input_state: ReportInputState, prompt_runner: PromptRunner | None = ...
) -> str: ...
